version: 0.2
phases:
  pre_build:
    commands:
    - EKS_NAME=[cicd]
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 763991179961.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    - REPOSITORY_URI=${REPO_ECR}
    - IMAGE_TAG=${IMAGE_TAG}
    - aws eks update-kubeconfig --name ${EKS_NAME}
    - kubectl version
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t helloworld .
    - docker tag helloworld:latest 763991179961.dkr.ecr.ap-southeast-1.amazonaws.com/helloworld:latest
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker images...
    - docker push 763991179961.dkr.ecr.ap-southeast-1.amazonaws.com/helloworld:latest
