kind: Namespace
apiVersion: v1
metadata:
  name: helloworld
  labels:
    name: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: helloworld
  name: helloworld-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: helloworld-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helloworld-app
    spec:
      containers:
      - image: 763991179961.dkr.ecr.ap-southeast-1.amazonaws.com/helloworld:latest
        imagePullPolicy: Always
        name: helloworld-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: helloworld
  name: helloworld-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: helloworld-app
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: helloworld
  name: helloworld-ingress-alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: helloworld-app
              servicePort: 80
